 No me gustaba está manera de configurar la interfaz, por lo que 
 si tienes que añadir algo aquí, haces lo mismo poniendolo desde 
 la web, en el editor de la interfaz de usuario > editor de 
 configuracion en bruto.
